# templates/argocd-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-admission-registration-role
rules:
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - validatingadmissionpolicybindings
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-admission-registration-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-admission-registration-role
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: {{ .Release.Namespace }}
